server:
    port: 8888

spring:
    datasource:
        username: evgenii
        password: 1234
        url: jdbc:postgresql://localhost:5432/tastyfasty
    liquibase:
        change-log: classpath*:migrations/master-changelog.yml

mybatis:
    configuration:
        map-underscore-to-camel-case: true
